import 'package:flutter/material.dart';

class AppStrings {
  static const Locale english = Locale('en', 'US');
  static const Locale hindi = Locale('hi', 'IN');
  static const Locale marathi = Locale('mr', 'IN');

  static const List<Locale> supportedLocales = [english, hindi, marathi];

  static const Map<String, Map<String, String>> translations = {
    'en': {
      // App Title
      'app_title': 'Smart Farming',

      // Authentication
      'login': 'Login',
      'logout': 'Logout',
      'select_role': 'Select Role',
      'choose_user_type': 'Choose how you want to use SmartFarmer',
      'farmer': 'Farmer',
      'crop_verifier': 'Crop Verifier',
      'admin': 'Admin',

      // Dashboard
      'dashboard': 'Dashboard',
      'profile': 'Profile',
      'crops': 'Crops',
      'verifications': 'Verifications',
      'reports': 'Reports',
      'settings': 'Settings',

      // Farmer Side
      'farmer_dashboard': 'Farmer Dashboard',
      'add_new_crop': 'Add New Crop',
      'view_profile': 'View Profile',
      'search_farmers': 'Search Farmers',
      'location_filter': 'Location Filter',
      'crop_details': 'Crop Details',
      'farmer_details': 'Farmer Details',

      // Forms
      'name': 'Name',
      'contact_number': 'Contact Number',
      'aadhaar_number': 'Aadhaar Number',
      'address': 'Address',
      'village': 'Village',
      'landmark': 'Nearby Landmark',
      'taluka': 'Taluka',
      'district': 'District',
      'pincode': 'Pincode',
      'crop_name': 'Crop Name',
      'area': 'Area (Acres)',
      'sowing_date': 'Sowing Date',
      'expected_harvest_date': 'Expected Harvest Date',
      'expected_yield': 'Expected Yield',
      'previous_crop': 'Previous Crop',
      'live_location': 'Live Location',
      'upload_images': 'Upload Images',
      'save': 'Save',
      'update': 'Update',
      'cancel': 'Cancel',
      'submit': 'Submit',

      // Crop Verifier Side
      'verifier_dashboard': 'Verifier Dashboard',
      'pending_verifications': 'Pending Verifications',
      'verified_crops': 'Verified Crops',
      'field_verification': 'Field Verification',
      'mark_verified': 'Mark as Verified',
      'mark_rejected': 'Mark as Rejected',
      'verification_comments': 'Verification Comments',
      'upload_verification_images': 'Upload Verification Images',

      // Admin Dashboard
      'admin_dashboard': 'Admin Dashboard',
      'total_farmers': 'Total Farmers',
      'total_crops': 'Total Crops',
      'crop_insights': 'Crop Insights',
      'location_insights': 'Location Insights',
      'export_data': 'Export Data',
      'generate_report': 'Generate Report',

      // AI Insights
      'ai_insights': 'AI Insights',
      'crop_age': 'Crop Age',
      'growth_stage': 'Growth Stage',
      'recommendations': 'Recommendations',
      'days_old': 'days old',
      'days_to_harvest': 'days to harvest',

      // Messages
      'data_saved_successfully': 'Data saved successfully',
      'data_updated_successfully': 'Data updated successfully',
      'verification_completed': 'Verification completed',
      'please_fill_all_fields': 'Please fill all required fields',
      'invalid_aadhaar': 'Invalid Aadhaar number (must be 12 digits)',
      'invalid_pincode': 'Invalid pincode (must be 6 digits)',
      'invalid_phone': 'Invalid phone number (must be 10 digits)',
      'location_permission_required': 'Location permission is required',
      'image_upload_failed': 'Image upload failed',
      'no_data_found': 'No data found',
      'search_farmers_placeholder': 'Search by name or ID...',
      'filter_by_location': 'Filter by location',

      // Status
      'pending': 'Pending',
      'verified': 'Verified',
      'rejected': 'Rejected',

      // Growth Stages
      'germination': 'Germination',
      'vegetative': 'Vegetative',
      'flowering': 'Flowering',
      'fruiting': 'Fruiting',
      'harvesting': 'Harvesting',
      'mature': 'Mature',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'edit': 'Edit',
      'view': 'View',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'close': 'Close',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',

      // Additional keys for dashboard screens
      'welcome': 'Welcome',
      'home': 'Home',
      'location': 'Location',
      'quick_actions': 'Quick Actions',
      'recent_crops': 'Recent Crops',
      'no_crops_found': 'No crops found',
      'no_crops_found_filter': 'No crops found matching your filter.',
      'no_crops_for_insights': 'No crops available for insights',
      'add_first_crop': 'Add your first crop',
      'error_loading_crops': 'Error loading crops',
      'edit_profile': 'Edit Profile',
      'add_crop': 'Add Crop',
      'language': 'Language',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'about': 'About',

      // Dashboard greetings and other static strings
      'good_morning': 'Good Morning!',
      'good_afternoon': 'Good Afternoon!',
      'good_evening': 'Good Evening!',
      'start_farming_journey':
          'Start your farming journey by adding your first crop',
      'my_crops': 'My Crops',
      'total_area': 'Total Area',
      'acres': 'acres',

      // Registration
      'registration': 'Registration',
      'personal_information': 'Personal Information',
      'address_information': 'Address Information',
      'full_name': 'Full Name',
      'name_required': 'Name is required',
      'phone_required': 'Phone number is required',
      'aadhaar_required': 'Aadhaar number is required',
      'village_required': 'Village is required',
      'taluka_required': 'Taluka is required',
      'district_required': 'District is required',
      'pincode_required': 'Pincode is required',
      'register': 'Register',
      'already_have_account': 'Already have an account?',

      // New keys for onboarding/registration
      'choose_language': 'Choose Language',
      'please_provide_basic_info': 'Please provide your basic information',
      'email': 'Email',
      'please_provide_address': 'Please provide your address',
      'create_secure_password': 'Create a secure password',
      'agree_terms': 'I agree to the terms and conditions',

      // New key for search farmer
      'search_farmer': 'Search Farmer',
      'search_crops': 'Search Crops',
      'view_reports': 'View Reports',

      // OTP & Mobile Verification
      'smart_farming_management': 'Smart Farming Management',
      'mobile_verification': 'Mobile Verification',
      'enter_mobile_number': 'Enter your mobile number to receive OTP',
      'enter_mobile_number_hint': 'Enter your 10-digit mobile number',
      'please_enter_mobile_number': 'Please enter your mobile number',
      'mobile_number_must_be_10_digits': 'Mobile number must be 10 digits',
      'otp': 'OTP',
      'enter_otp': 'Enter OTP',
      'enter_otp_hint': 'Enter 6-digit OTP',
      'please_enter_valid_otp': 'Please enter a valid 6-digit OTP',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'resend_otp': 'Resend OTP',
      'back_to_mobile_number': 'Back to Mobile Number',
      'enter_otp_message': 'Enter the 6-digit OTP sent to {number}',
      // General
      'mobile_number': 'Mobile Number',
      'security': 'Security',
      // Maharashtra Districts
      'Maharashtra': 'Maharashtra',
      'Ahmednagar': 'Ahmednagar',
      'Akola': 'Akola',
      'Amravati': 'Amravati',
      'Aurangabad': 'Aurangabad',
      'Beed': 'Beed',
      'Bhandara': 'Bhandara',
      'Buldhana': 'Buldhana',
      'Chandrapur': 'Chandrapur',
      'Dhule': 'Dhule',
      'Gadchiroli': 'Gadchiroli',
      'Gondia': 'Gondia',
      'Hingoli': 'Hingoli',
      'Jalgaon': 'Jalgaon',
      'Jalna': 'Jalna',
      'Kolhapur': 'Kolhapur',
      'Latur': 'Latur',
      'Mumbai City': 'Mumbai City',
      'Mumbai Suburban': 'Mumbai Suburban',
      'Nagpur': 'Nagpur',
      'Nanded': 'Nanded',
      'Nandurbar': 'Nandurbar',
      'Nashik': 'Nashik',
      'Osmanabad': 'Osmanabad',
      'Parbhani': 'Parbhani',
      'Pune': 'Pune',
      'Raigad': 'Raigad',
      'Ratnagiri': 'Ratnagiri',
      'Sangli': 'Sangli',
      'Satara': 'Satara',
      'Sindhudurg': 'Sindhudurg',
      'Solapur': 'Solapur',
      'Thane': 'Thane',
      'Wardha': 'Wardha',
      'Washim': 'Washim',
      'Yavatmal': 'Yavatmal',
      // Maharashtra Talukas/Cities
      'Shrirampur': 'Shrirampur',
      'Rahata': 'Rahata',
      'Rahuri': 'Rahuri',
      'Sangamner': 'Sangamner',
      'Kopargaon': 'Kopargaon',
      'Akole': 'Akole',
      'Nevasa': 'Nevasa',
      'Shevgaon': 'Shevgaon',
      'Pathardi': 'Pathardi',
      'Parner': 'Parner',
      'Jamkhed': 'Jamkhed',
      'Karjat': 'Karjat',
      'Balapur': 'Balapur',
      'Patur': 'Patur',
      'Telhara': 'Telhara',
      'Akot': 'Akot',
      'Murtijapur': 'Murtijapur',
      'Chandur Railway': 'Chandur Railway',
      'Chikhaldara': 'Chikhaldara',
      'Daryapur': 'Daryapur',
      'Dhamangaon Railway': 'Dhamangaon Railway',
      'Morshi': 'Morshi',
      'Nandgaon-Khandeshwar': 'Nandgaon-Khandeshwar',
      'Anjangaon Surji': 'Anjangaon Surji',
      'Achalpur': 'Achalpur',
      'Gangapur': 'Gangapur',
      'Vaijapur': 'Vaijapur',
      'Sillod': 'Sillod',
      'Kannad': 'Kannad',
      'Paithan': 'Paithan',
      'Khuldabad': 'Khuldabad',
      'Phulambri': 'Phulambri',
      'Ashti': 'Ashti',
      'Ambejogai': 'Ambejogai',
      'Patoda': 'Patoda',
      'Kaij': 'Kaij',
      'Georai': 'Georai',
      'Majalgaon': 'Majalgaon',
      'Parli': 'Parli',
      'Shirur (Beed)': 'Shirur (Beed)',
      'Tumsar': 'Tumsar',
      'Sakoli': 'Sakoli',
      'Lakhani': 'Lakhani',
      'Mohadi': 'Mohadi',
      'Pauni': 'Pauni',
      'Chikhli': 'Chikhli',
      'Mehkar': 'Mehkar',
      'Jalgaon Jamod': 'Jalgaon Jamod',
      'Sangrampur': 'Sangrampur',
      'Malkapur': 'Malkapur',
      'Deulgaon Raja': 'Deulgaon Raja',
      'Motala': 'Motala',
      'Nandura': 'Nandura',
      'Shegaon': 'Shegaon',
      'Warora': 'Warora',
      'Bhadravati': 'Bhadravati',
      'Chimur': 'Chimur',
      'Nagbhid': 'Nagbhid',
      'Mul': 'Mul',
      'Saoli': 'Saoli',
      'Rajura': 'Rajura',
      'Pombhurna': 'Pombhurna',
      'Ballarpur': 'Ballarpur',
      'Gondpipri': 'Gondpipri',
      'Korpana': 'Korpana',
      'Shirpur': 'Shirpur',
      'Sakri': 'Sakri',
      'Sindkheda': 'Sindkheda',
      'Aheri': 'Aheri',
      'Chamorshi': 'Chamorshi',
      'Etapalli': 'Etapalli',
      'Armori': 'Armori',
      'Desaiganj (Wadsa)': 'Desaiganj (Wadsa)',
      'Korchi': 'Korchi',
      'Kurkheda': 'Kurkheda',
      'Mulchera': 'Mulchera',
      'Tirora': 'Tirora',
      'Goregaon': 'Goregaon',
      'Amgaon': 'Amgaon',
      'Arjuni Morgaon': 'Arjuni Morgaon',
      'Deori': 'Deori',
      'Sadak Arjuni': 'Sadak Arjuni',
      'Salekasa': 'Salekasa',
      'Kalamnuri': 'Kalamnuri',
      'Basmath': 'Basmath',
      'Sengaon': 'Sengaon',
      'Bhusawal': 'Bhusawal',
      'Jamner': 'Jamner',
      'Chalisgaon': 'Chalisgaon',
      'Erandol': 'Erandol',
      'Yawal': 'Yawal',
      'Amalner': 'Amalner',
      'Pachora': 'Pachora',
      'Parola': 'Parola',
      'Dharangaon': 'Dharangaon',
      'Bhokardan': 'Bhokardan',
      'Jaffrabad': 'Jaffrabad',
      'Ambad': 'Ambad',
      'Badnapur': 'Badnapur',
      'Mantha': 'Mantha',
      'Partur': 'Partur',
      'Ghansawangi': 'Ghansawangi',
      'Karveer': 'Karveer',
      'Gaganbawada': 'Gaganbawada',
      'Radhanagari': 'Radhanagari',
      'Ajra': 'Ajra',
      'Bhudargad': 'Bhudargad',
      'Chandgad': 'Chandgad',
      'Gadhinglaj': 'Gadhinglaj',
      'Hatkanangale': 'Hatkanangale',
      'Kagal': 'Kagal',
      'Panhala': 'Panhala',
      'Shirol': 'Shirol',
      'Ahmadpur': 'Ahmadpur',
      'Udgir': 'Udgir',
      'Nilanga': 'Nilanga',
      'Ausa': 'Ausa',
      'Chakur': 'Chakur',
      'Deoni': 'Deoni',
      'Renapur': 'Renapur',
      'Shirur Anantpal': 'Shirur Anantpal',
      'Katol': 'Katol',
      'Narkhed': 'Narkhed',
      'Kalmeshwar': 'Kalmeshwar',
      'Hingna': 'Hingna',
      'Umred': 'Umred',
      'Parseoni': 'Parseoni',
      'Ramtek': 'Ramtek',
      'Bhiwapur': 'Bhiwapur',
      'Kuhi': 'Kuhi',
      'Mauda': 'Mauda',
      'Kinwat': 'Kinwat',
      'Hadgaon': 'Hadgaon',
      'Bhokar': 'Bhokar',
      'Loha': 'Loha',
      'Naigaon': 'Naigaon',
      'Mukhed': 'Mukhed',
      'Deglur': 'Deglur',
      'Kandhar': 'Kandhar',
      'Himayatnagar': 'Himayatnagar',
      'Shahada': 'Shahada',
      'Taloda': 'Taloda',
      'Navapur': 'Navapur',
      'Akkalkuwa': 'Akkalkuwa',
      'Akrani (Dhadgaon)': 'Akrani (Dhadgaon)',
      'Malegaon': 'Malegaon',
      'Sinnar': 'Sinnar',
      'Igatpuri': 'Igatpuri',
      'Kalwan': 'Kalwan',
      'Dindori': 'Dindori',
      'Chandwad': 'Chandwad',
      'Deola': 'Deola',
      'Niphad': 'Niphad',
      'Peth': 'Peth',
      'Trimbakeshwar': 'Trimbakeshwar',
      'Baglan': 'Baglan',
      'Yevla': 'Yevla',
      'Tuljapur': 'Tuljapur',
      'Paranda': 'Paranda',
      'Bhum': 'Bhum',
      'Kalamb': 'Kalamb',
      'Lohara': 'Lohara',
      'Umarga': 'Umarga',
      'Vashi': 'Vashi',
      'Gangakhed': 'Gangakhed',
      'Pathri': 'Pathri',
      'Sonpeth': 'Sonpeth',
      'Manwat': 'Manwat',
      'Jintur': 'Jintur',
      'Purna': 'Purna',
      'Palam': 'Palam',
      'Sailu': 'Sailu',
      'Pune City': 'Pune City',
      'Haveli': 'Haveli',
      'Mulshi': 'Mulshi',
      'Bhor': 'Bhor',
      'Baramati': 'Baramati',
      'Indapur': 'Indapur',
      'Junnar': 'Junnar',
      'Daund': 'Daund',
      'Ambegaon': 'Ambegaon',
      'Shirur': 'Shirur',
      'Velhe': 'Velhe',
      'Purandar': 'Purandar',
      'Mawal': 'Mawal',
      'Khed': 'Khed',
      'Alibag': 'Alibag',
      'Pen': 'Pen',
      'Mahad': 'Mahad',
      'Murud': 'Murud',
      'Roha': 'Roha',
      'Shrivardhan': 'Shrivardhan',
      'Tala': 'Tala',
      'Uran': 'Uran',
      'Khalapur': 'Khalapur',
      'Mangaon': 'Mangaon',
      'Poladpur': 'Poladpur',
      'Sudhagad Pali': 'Sudhagad Pali',
      'Mandangad': 'Mandangad',
      'Dapoli': 'Dapoli',
      'Guhagar': 'Guhagar',
      'Chiplun': 'Chiplun',
      'Sangameshwar': 'Sangameshwar',
      'Lanja': 'Lanja',
      'Rajapur': 'Rajapur',
      'Miraj': 'Miraj',
      'Tasgaon': 'Tasgaon',
      'Kavathemahankal': 'Kavathemahankal',
      'Jath': 'Jath',
      'Khanapur': 'Khanapur',
      'Palus': 'Palus',
      'Atpadi': 'Atpadi',
      'Walwa': 'Walwa',
      'Shirala': 'Shirala',
      'Karad': 'Karad',
      'Wai': 'Wai',
      'Patan': 'Patan',
      'Mahabaleshwar': 'Mahabaleshwar',
      'Phaltan': 'Phaltan',
      'Khatav': 'Khatav',
      'Koregaon': 'Koregaon',
      'Jaoli': 'Jaoli',
      'Man': 'Man',
      'Kudal': 'Kudal',
      'Sawantwadi': 'Sawantwadi',
      'Dodamarg': 'Dodamarg',
      'Vengurla': 'Vengurla',
      'Malvan': 'Malvan',
      'Devgad': 'Devgad',
      'Kankavli': 'Kankavli',
      'Solapur North': 'Solapur North',
      'Solapur South': 'Solapur South',
      'Barshi': 'Barshi',
      'Madha': 'Madha',
      'Karmala': 'Karmala',
      'Mohol': 'Mohol',
      'Pandharpur': 'Pandharpur',
      'Sangole': 'Sangole',
      'Akkalkot': 'Akkalkot',
      'Malshiras': 'Malshiras',
      'Kalyan': 'Kalyan',
      'Bhiwandi': 'Bhiwandi',
      'Murbad': 'Murbad',
      'Ulhasnagar': 'Ulhasnagar',
      'Ambarnath': 'Ambarnath',
      'Shahapur': 'Shahapur',
      'Hinganghat': 'Hinganghat',
      'Deoli': 'Deoli',
      'Arvi': 'Arvi',
      'Seloo': 'Seloo',
      'Samudrapur': 'Samudrapur',
      'Mangrulpir': 'Mangrulpir',
      'Karanja': 'Karanja',
      'Manora': 'Manora',
      'Malegaon (Washim)': 'Malegaon (Washim)',
      'Risod': 'Risod',
      'Pusad': 'Pusad',
      'Umarkhed': 'Umarkhed',
      'Digras': 'Digras',
      'Arni': 'Arni',
      'Darwha': 'Darwha',
      'Kelapur': 'Kelapur',
      'Ghatanji': 'Ghatanji',
      'Ner': 'Ner',
      'Mahagaon': 'Mahagaon',
      'Ralegaon': 'Ralegaon',
      'Babulgaon': 'Babulgaon',
    },
    'hi': {
      // App Title
      'app_title': 'स्मार्ट फार्मर',

      // Authentication
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'select_role': 'भूमिका चुनें',
      'choose_user_type': 'स्मार्टफार्मर का उपयोग कैसे करना चाहते हैं चुनें',
      'farmer': 'किसान',
      'crop_verifier': 'फसल सत्यापनकर्ता',
      'admin': 'प्रशासक',

      // Dashboard
      'dashboard': 'डैशबोर्ड',
      'profile': 'प्रोफाइल',
      'crops': 'फसलें',
      'verifications': 'सत्यापन',
      'reports': 'रिपोर्ट',
      'settings': 'सेटिंग्स',

      // Farmer Side
      'farmer_dashboard': 'किसान डैशबोर्ड',
      'add_new_crop': 'नई फसल जोड़ें',
      'view_profile': 'प्रोफाइल देखें',
      'search_farmers': 'किसान खोजें',
      'location_filter': 'स्थान फ़िल्टर',
      'crop_details': 'फसल विवरण',
      'farmer_details': 'किसान विवरण',

      // Forms
      'name': 'नाम',
      'contact_number': 'संपर्क संख्या',
      'aadhaar_number': 'आधार संख्या',
      'address': 'पता',
      'village': 'गाँव',
      'landmark': 'निकटवर्ती स्थल',
      'taluka': 'तालुका',
      'district': 'जिला',
      'pincode': 'पिन कोड',
      'crop_name': 'फसल का नाम',
      'area': 'क्षेत्र (एकड़)',
      'sowing_date': 'बुवाई की तारीख',
      'expected_harvest_date': 'अनुमानित कटाई की तारीख',
      'expected_yield': 'अनुमानित उपज',
      'previous_crop': 'पिछली फसल',
      'live_location': 'लाइव स्थान',
      'upload_images': 'छवियां अपलोड करें',
      'save': 'सहेजें',
      'update': 'अपडेट',
      'cancel': 'रद्द करें',
      'submit': 'सबमिट करें',

      // Crop Verifier Side
      'verifier_dashboard': 'सत्यापनकर्ता डैशबोर्ड',
      'pending_verifications': 'लंबित सत्यापन',
      'verified_crops': 'सत्यापित फसलें',
      'field_verification': 'क्षेत्र सत्यापन',
      'mark_verified': 'सत्यापित के रूप में चिह्नित करें',
      'mark_rejected': 'अस्वीकृत के रूप में चिह्नित करें',
      'verification_comments': 'सत्यापन टिप्पणियां',
      'upload_verification_images': 'सत्यापन छवियां अपलोड करें',

      // Admin Dashboard
      'admin_dashboard': 'प्रशासक डैशबोर्ड',
      'total_farmers': 'कुल किसान',
      'total_crops': 'कुल फसलें',
      'crop_insights': 'फसल अंतर्दृष्टि',
      'location_insights': 'स्थान अंतर्दृष्टि',
      'export_data': 'डेटा निर्यात करें',
      'generate_report': 'रिपोर्ट तैयार करें',

      // AI Insights
      'ai_insights': 'एआई अंतर्दृष्टि',
      'crop_age': 'फसल की आयु',
      'growth_stage': 'विकास चरण',
      'recommendations': 'सिफारिशें',
      'days_old': 'दिन पुराना',
      'days_to_harvest': 'कटाई में दिन',

      // Messages
      'data_saved_successfully': 'डेटा सफलतापूर्वक सहेजा गया',
      'data_updated_successfully': 'डेटा सफलतापूर्वक अपडेट किया गया',
      'verification_completed': 'सत्यापन पूरा हुआ',
      'please_fill_all_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
      'invalid_aadhaar': 'अमान्य आधार संख्या (12 अंक होने चाहिए)',
      'invalid_pincode': 'अमान्य पिन कोड (6 अंक होने चाहिए)',
      'invalid_phone': 'अमान्य फोन संख्या (10 अंक होने चाहिए)',
      'location_permission_required': 'स्थान अनुमति आवश्यक है',
      'image_upload_failed': 'छवि अपलोड विफल',
      'no_data_found': 'कोई डेटा नहीं मिला',
      'search_farmers_placeholder': 'नाम या आईडी से खोजें...',
      'filter_by_location': 'स्थान के अनुसार फ़िल्टर करें',

      // Status
      'pending': 'लंबित',
      'verified': 'सत्यापित',
      'rejected': 'अस्वीकृत',

      // Growth Stages
      'germination': 'अंकुरण',
      'vegetative': 'वानस्पतिक',
      'flowering': 'फूलना',
      'fruiting': 'फलना',
      'harvesting': 'कटाई',
      'mature': 'परिपक्व',

      // Common
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'warning': 'चेतावनी',
      'info': 'जानकारी',
      'confirm': 'पुष्टि करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'view': 'देखें',
      'back': 'वापस',
      'next': 'अगला',
      'previous': 'पिछला',
      'close': 'बंद करें',
      'ok': 'ठीक है',
      'yes': 'हाँ',
      'no': 'नहीं',

      // Additional keys for dashboard screens
      'welcome': 'स्वागत',
      'home': 'घर',
      'location': 'स्थान',
      'quick_actions': 'त्वरित कार्य',
      'recent_crops': 'हाल की फसलें',
      'no_crops_found': 'कोई फसल नहीं मिली',
      'no_crops_found_filter':
          'आपके फ़िल्टर से मेल खाने वाली कोई फसल नहीं मिली।',
      'no_crops_for_insights': 'अंतर्दृष्टि के लिए कोई फसल उपलब्ध नहीं है',
      'add_first_crop': 'अपनी पहली फसल जोड़ें',
      'error_loading_crops': 'फसल लोड करने में त्रुटि',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'add_crop': 'फसल जोड़ें',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'help_support': 'सहायता और समर्थन',
      'about': 'बारे में',

      // Dashboard greetings and other static strings
      'good_morning': 'सुप्रभात!',
      'good_afternoon': 'शुभ दोपहर!',
      'good_evening': 'शुभ संध्या!',
      'start_farming_journey':
          'अपनी कृषि यात्रा अपनी पहली फसल जोड़कर शुरू करें',
      'my_crops': 'मेरी फसलें',
      'total_area': 'कुल क्षेत्र',
      'acres': 'एकड़',

      // Registration
      'registration': 'पंजीकरण',
      'personal_information': 'व्यक्तिगत जानकारी',
      'address_information': 'पता जानकारी',
      'full_name': 'पूरा नाम',
      'name_required': 'नाम आवश्यक है',
      'phone_required': 'फोन नंबर आवश्यक है',
      'aadhaar_required': 'आधार नंबर आवश्यक है',
      'village_required': 'गाँव आवश्यक है',
      'taluka_required': 'तालुका आवश्यक है',
      'district_required': 'जिला आवश्यक है',
      'pincode_required': 'पिन कोड आवश्यक है',
      'register': 'पंजीकरण करें',
      'already_have_account': 'पहले से खाता है?',

      // New keys for onboarding/registration
      'choose_language': 'भाषा निवडा',
      'please_provide_basic_info': 'कृपया अपनी मूलभूत जानकारी द्या',
      'email': 'ईमेल',
      'please_provide_address': 'कृपया अपना पता द्या',
      'create_secure_password': 'सुरक्षित पासवर्ड तयार करा',
      'agree_terms': 'मी नियम व अटींना सहमती देतो',

      // New key for search farmer
      'search_farmer': 'किसान खोजें',
      'search_crops': 'फसलें खोजें',
      'view_reports': 'रिपोर्ट देखें',

      // OTP & Mobile Verification
      'smart_farming_management': 'स्मार्ट फार्मिंग प्रबंधन',
      'mobile_verification': 'मोबाइल सत्यापन',
      'enter_mobile_number':
          'ओटीपी प्राप्त करने के लिए अपना मोबाइल नंबर दर्ज करें',
      'enter_mobile_number_hint': 'अपना 10-अंकों का मोबाइल नंबर दर्ज करें',
      'please_enter_mobile_number': 'कृपया अपना मोबाइल नंबर दर्ज करें',
      'mobile_number_must_be_10_digits': 'मोबाइल नंबर 10 अंक का होना चाहिए',
      'otp': 'ओटीपी',
      'enter_otp': 'ओटीपी दर्ज करें',
      'enter_otp_hint': '6-अंकों का ओटीपी दर्ज करें',
      'please_enter_valid_otp': 'कृपया मान्य 6-अंकों का ओटीपी दर्ज करें',
      'send_otp': 'ओटीपी भेजें',
      'verify_otp': 'ओटीपी सत्यापित करें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'back_to_mobile_number': 'मोबाइल नंबर पर वापस जाएं',
      'enter_otp_message': '{number} पर भेजा गया 6-अंकों का ओटीपी दर्ज करें',
      // General
      'mobile_number': 'मोबाइल नंबर',
      'security': 'सुरक्षा',
      // Maharashtra Districts
      'Maharashtra': 'महाराष्ट्र',
      'Ahmednagar': 'अहमदनगर',
      'Akola': 'अकोला',
      'Amravati': 'अमरावती',
      'Aurangabad': 'औरंगाबाद',
      'Beed': 'बीड',
      'Bhandara': 'भंडारा',
      'Buldhana': 'बुलढाणा',
      'Chandrapur': 'चंद्रपुर',
      'Dhule': 'धुले',
      'Gadchiroli': 'गडचिरोली',
      'Gondia': 'गोंदिया',
      'Hingoli': 'हिंगोली',
      'Jalgaon': 'जलगांव',
      'Jalna': 'जालना',
      'Kolhapur': 'कोल्हापुर',
      'Latur': 'लातूर',
      'Mumbai City': 'मुंबई शहर',
      'Mumbai Suburban': 'मुंबई उपनगर',
      'Nagpur': 'नागपुर',
      'Nanded': 'नांदेड',
      'Nandurbar': 'नंदुरबार',
      'Nashik': 'नासिक',
      'Osmanabad': 'उस्मानाबाद',
      'Parbhani': 'परभणी',
      'Pune': 'पुणे',
      'Raigad': 'रायगढ़',
      'Ratnagiri': 'रत्नागिरी',
      'Sangli': 'सांगली',
      'Satara': 'सातारा',
      'Sindhudurg': 'सिंधुदुर्ग',
      'Solapur': 'सोलापुर',
      'Thane': 'ठाणे',
      'Wardha': 'वर्धा',
      'Washim': 'वाशीम',
      'Yavatmal': 'यवतमाळ',
      // Maharashtra Talukas/Cities
      'Shrirampur': 'श्रीरामपुर',
      'Rahata': 'राहता',
      'Rahuri': 'राहुरी',
      'Sangamner': 'संगमनर',
      'Kopargaon': 'कोपरगाव',
      'Akole': 'अकोला',
      'Nevasa': 'नेवासा',
      'Shevgaon': 'शेवगाव',
      'Pathardi': 'पाठर्दी',
      'Parner': 'परनर',
      'Jamkhed': 'जामखेड',
      'Balapur': 'बलपुर',
      'Patur': 'पाटूर',
      'Telhara': 'टेलहरा',
      'Akot': 'अकोट',
      'Murtijapur': 'मुर्तिजपुर',
      'Chandur Railway': 'चंदुर रेलवे',
      'Chikhaldara': 'चिकखलदारा',
      'Daryapur': 'दर्यापुर',
      'Dhamangaon Railway': 'धामागंव रेलवे',
      'Morshi': 'मोर्शी',
      'Nandgaon-Khandeshwar': 'नंदगाव-खंडेशवर',
      'Anjangaon Surji': 'अंजंगाव सुर्जी',
      'Achalpur': 'अचलपुर',
      'Gangapur': 'गंगापुर',
      'Vaijapur': 'वैजापुर',
      'Sillod': 'सिलोड',
      'Kannad': 'कन्नाड',
      'Paithan': 'पैथान',
      'Khuldabad': 'खुलढाबाद',
      'Phulambri': 'फुलम्बरी',
      'Ashti': 'अश्ती',
      'Ambejogai': 'अम्बेजोगै',
      'Patoda': 'पाटोदा',
      'Kaij': 'कैज',
      'Georai': 'गेओराई',
      'Majalgaon': 'मजलागाव',
      'Parli': 'परली',
      'Shirur (Beed)': 'शिरुर (बीड)',
      'Tumsar': 'तुमसर',
      'Sakoli': 'साकोली',
      'Lakhani': 'लाखानी',
      'Mohadi': 'मोहादी',
      'Pauni': 'पौनी',
      'Chikhli': 'चिकखली',
      'Mehkar': 'मेहकर',
      'Jalgaon Jamod': 'जलगांव जामोड',
      'Sangrampur': 'संगरमपुर',
      'Malkapur': 'मलकपुर',
      'Deulgaon Raja': 'देवलगाव राजा',
      'Motala': 'मोतला',
      'Nandura': 'नंदुरा',
      'Shegaon': 'शेगाव',
      'Warora': 'वरोरा',
      'Bhadravati': 'भद्रावती',
      'Chimur': 'चिमुर',
      'Nagbhid': 'नागभिद',
      'Mul': 'मुल',
      'Saoli': 'सावोली',
      'Rajura': 'राजुरा',
      'Pombhurna': 'पोम्बुर्ना',
      'Ballarpur': 'बलरपुर',
      'Gondpipri': 'गोंदपिरी',
      'Korpana': 'कोरपाना',
      'Shirpur': 'शिरपुर',
      'Sakri': 'साकरी',
      'Sindkheda': 'सिंधकेडा',
      'Aheri': 'अहेरी',
      'Chamorshi': 'चामोर्शी',
      'Etapalli': 'एटापली',
      'Armori': 'अर्मोरी',
      'Desaiganj (Wadsa)': 'देसागंज (वाडसा)',
      'Korchi': 'कोरची',
      'Kurkheda': 'कुर्खेडा',
      'Mulchera': 'मुलचेरा',
      'Tirora': 'तिरोरा',
      'Goregaon': 'गोरेगाव',
      'Amgaon': 'अमगाव',
      'Arjuni Morgaon': 'अर्जुनी मोरगाव',
      'Deori': 'देवोरी',
      'Sadak Arjuni': 'सादक अर्जुनी',
      'Salekasa': 'सलेकासा',
      'Kalamnuri': 'कालमनुरी',
      'Basmath': 'बस्मात',
      'Sengaon': 'सेंगाव',
      'Bhusawal': 'भुसावल',
      'Jamner': 'जामनर',
      'Chalisgaon': 'चलिसगाव',
      'Erandol': 'एरंदोल',
      'Yawal': 'यावल',
      'Amalner': 'अमलनर',
      'Pachora': 'पचोरा',
      'Parola': 'परोला',
      'Dharangaon': 'धारंगाव',
      'Bhokardan': 'भोकरदान',
      'Jaffrabad': 'जफ्राबाद',
      'Ambad': 'अम्बाद',
      'Badnapur': 'बदनपुर',
      'Mantha': 'मंथा',
      'Partur': 'पारतूर',
      'Ghansawangi': 'घंसावांगी',
      'Karveer': 'कर्वेयर',
      'Gaganbawada': 'गगनबावदा',
      'Radhanagari': 'राधानागरी',
      'Ajra': 'अज्रा',
      'Bhudargad': 'भुदारगड',
      'Chandgad': 'चंदगड',
      'Gadhinglaj': 'गढ़िंगलाज',
      'Hatkanangale': 'हटकानांगाले',
      'Kagal': 'कागल',
      'Panhala': 'पांहाला',
      'Shirol': 'शिरोल',
      'Ahmadpur': 'अहमदपुर',
      'Udgir': 'उद्गिर',
      'Nilanga': 'निलंगा',
      'Ausa': 'अवुसा',
      'Chakur': 'चकुर',
      'Deoni': 'देओनी',
      'Renapur': 'रेनापुर',
      'Shirur Anantpal': 'शिरुर अनन्तपाल',
      'Katol': 'काटोल',
      'Narkhed': 'नरखेड',
      'Kalmeshwar': 'कालमेशवर',
      'Hingna': 'हिंगना',
      'Umred': 'उमरेड',
      'Parseoni': 'परेसोनी',
      'Ramtek': 'रामटेक',
      'Bhiwapur': 'भिवावुर',
      'Kuhi': 'कुही',
      'Mauda': 'मौदा',
      'Kinwat': 'किनवत',
      'Hadgaon': 'हदगाव',
      'Bhokar': 'भोकर',
      'Loha': 'लोहा',
      'Naigaon': 'नाइगाव',
      'Mukhed': 'मुखेड',
      'Deglur': 'देगलूर',
      'Kandhar': 'कंधर',
      'Himayatnagar': 'हिमायतनगर',
      'Shahada': 'शाहदा',
      'Taloda': 'तालोदा',
      'Navapur': 'नवपुर',
      'Akkalkuwa': 'अक्कलकुवा',
      'Akrani (Dhadgaon)': 'अक्रनी (धादगाव)',
      'Malegaon': 'मलेगाव',
      'Sinnar': 'सिननर',
      'Igatpuri': 'इगतपुरी',
      'Kalwan': 'कालवान',
      'Dindori': 'दिनदोरी',
      'Chandwad': 'चंदवद',
      'Deola': 'देओला',
      'Niphad': 'निपहाड',
      'Peth': 'पेट',
      'Trimbakeshwar': 'त्रिम्बकेशवर',
      'Baglan': 'बागलन',
      'Yevla': 'येवला',
      'Tuljapur': 'तुलजपुर',
      'Paranda': 'परंदा',
      'Bhum': 'भूम',
      'Kalamb': 'कालंब',
      'Lohara': 'लोहारा',
      'Umarga': 'उमारगा',
      'Vashi': 'वाशी',
      'Gangakhed': 'गंगकेड',
      'Pathri': 'पाठ्री',
      'Sonpeth': 'सोनपेट',
      'Manwat': 'मनवत',
      'Jintur': 'जिंतूर',
      'Purna': 'पुरंदा',
      'Palam': 'पालम',
      'Sailu': 'सैलु',
      'Pune City': 'पुणे शहर',
      'Haveli': 'हवेली',
      'Mulshi': 'मुलशी',
      'Bhor': 'भोर',
      'Baramati': 'बरामती',
      'Indapur': 'इंदापुर',
      'Junnar': 'जुन्नार',
      'Daund': 'दौंड',
      'Ambegaon': 'अम्बेगाव',
      'Shirur': 'शिरुर',
      'Velhe': 'वेले',
      'Purandar': 'पुरंदार',
      'Mawal': 'मवल',
      'Khed': 'खेड',
      'Alibag': 'अलिबाग',
      'Pen': 'पेन',
      'Mahad': 'महादेव',
      'Murud': 'मुरुद',
      'Roha': 'रोहा',
      'Shrivardhan': 'श्रीवर्धन',
      'Tala': 'ताला',
      'Uran': 'उराण',
      'Karjat': 'कर्जत',
      'Khalapur': 'खलपुर',
      'Mangaon': 'मंगाव',
      'Poladpur': 'पोलदपुर',
      'Sudhagad Pali': 'सुधागद पाली',
      'Mandangad': 'मंदंगाड',
      'Dapoli': 'दापोली',
      'Guhagar': 'गुहागर',
      'Chiplun': 'चिपलुंड',
      'Sangameshwar': 'संगमेशवर',
      'Lanja': 'लांजा',
      'Rajapur': 'राजापुर',
      'Miraj': 'मिराज',
      'Tasgaon': 'तसगाव',
      'Kavathemahankal': 'कावथेमहांकल',
      'Jath': 'जठ',
      'Khanapur': 'खानपुर',
      'Palus': 'पालुस',
      'Atpadi': 'अत्पाडी',
      'Walwa': 'वालवा',
      'Shirala': 'शिरला',
      'Karad': 'कराड',
      'Wai': 'वै',
      'Patan': 'पाटन',
      'Mahabaleshwar': 'महाभालेश्वर',
      'Phaltan': 'फाल्टन',
      'Khatav': 'खटवा',
      'Koregaon': 'कोरेगाव',
      'Jaoli': 'जावली',
      'Man': 'मान',
      'Kudal': 'कुडल',
      'Sawantwadi': 'सावंतवाडी',
      'Dodamarg': 'दोदामारग',
      'Vengurla': 'वेंगुरला',
      'Malvan': 'मल्वान',
      'Devgad': 'देवगड',
      'Kankavli': 'कंकवली',
      'Solapur North': 'सोलापुर उत्तर',
      'Solapur South': 'सोलापुर दक्षिण',
      'Barshi': 'बर्शी',
      'Madha': 'मधा',
      'Karmala': 'कर्माला',
      'Mohol': 'मोहोल',
      'Pandharpur': 'पंधारपुर',
      'Sangole': 'संगोले',
      'Akkalkot': 'अक्कलकोट',
      'Malshiras': 'मल्शिरस',
      'Kalyan': 'कल्याण',
      'Bhiwandi': 'भिवाणदी',
      'Murbad': 'मुर्बाद',
      'Ulhasnagar': 'उल्हसनगर',
      'Ambarnath': 'अम्बरनाथ',
      'Shahapur': 'शाहपुर',
      'Hinganghat': 'हिंगंगट',
      'Deoli': 'देओली',
      'Arvi': 'अर्वी',
      'Seloo': 'सेलू',
      'Samudrapur': 'समुद्रपुर',
      'Mangrulpir': 'मंगरुल्पिर',
      'Karanja': 'करंजा',
      'Manora': 'मनोरा',
      'Malegaon (Washim)': 'मलेगाव (वाशिम)',
      'Risod': 'रिसोड',
      'Pusad': 'पुसाड',
      'Umarkhed': 'उमरकड',
      'Digras': 'दिग्रस',
      'Arni': 'अर्नी',
      'Darwha': 'दर्वाहा',
      'Kelapur': 'केलापुर',
      'Ghatanji': 'घटानजी',
      'Ner': 'नेर',
      'Mahagaon': 'महागाव',
      'Ralegaon': 'रालेगाव',
      'Babulgaon': 'बाबुलगाव',
    },
    'mr': {
      // App Title
      'app_title': 'स्मार्ट शेतकरी',

      // Authentication
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'select_role': 'भूमिका निवडा',
      'choose_user_type': 'तुम्ही स्मार्टफार्मर कसा वापरायचा आहे ते निवडा',
      'farmer': 'शेतकरी',
      'crop_verifier': 'पिक सत्यापनकर्ता',
      'admin': 'प्रशासक',

      // Dashboard
      'dashboard': 'डॅशबोर्ड',
      'profile': 'प्रोफाइल',
      'crops': 'पिके',
      'verifications': 'सत्यापन',
      'reports': 'अहवाल',
      'settings': 'सेटिंग्ज',

      // Farmer Side
      'farmer_dashboard': 'शेतकरी डॅशबोर्ड',
      'add_new_crop': 'नवीन पिक जोडा',
      'view_profile': 'प्रोफाइल पहा',
      'search_farmers': 'शेतकरी शोधा',
      'location_filter': 'स्थान फिल्टर',
      'crop_details': 'पिक तपशील',
      'farmer_details': 'शेतकरी तपशील',

      // Forms
      'name': 'नाव',
      'contact_number': 'संपर्क क्रमांक',
      'aadhaar_number': 'आधार क्रमांक',
      'address': 'पत्ता',
      'village': 'गाव',
      'landmark': 'जवळील खुण',
      'taluka': 'तालुका',
      'district': 'जिल्हा',
      'pincode': 'पिन कोड',
      'crop_name': 'पिकाचे नाव',
      'area': 'क्षेत्र (एकर)',
      'sowing_date': 'पेरणी तारीख',
      'expected_harvest_date': 'अपेक्षित कापणी तारीख',
      'expected_yield': 'अपेक्षित उत्पन्न',
      'previous_crop': 'मागील पिक',
      'live_location': 'लाइव्ह स्थान',
      'upload_images': 'प्रतिमा अपलोड करा',
      'save': 'जतन करा',
      'update': 'अपडेट करा',
      'cancel': 'रद्द करा',
      'submit': 'सबमिट करा',

      // Crop Verifier Side
      'verifier_dashboard': 'सत्यापनकर्ता डॅशबोर्ड',
      'pending_verifications': 'प्रलंबित सत्यापन',
      'verified_crops': 'सत्यापित पिके',
      'field_verification': 'शेत सत्यापन',
      'mark_verified': 'सत्यापित म्हणून चिन्हांकित करा',
      'mark_rejected': 'नाकारले म्हणून चिन्हांकित करा',
      'verification_comments': 'सत्यापन टिप्पण्या',
      'upload_verification_images': 'सत्यापन प्रतिमा अपलोड करा',

      // Admin Dashboard
      'admin_dashboard': 'प्रशासक डॅशबोर्ड',
      'total_farmers': 'एकूण शेतकरी',
      'total_crops': 'एकूण पिके',
      'crop_insights': 'पिक अंतर्दृष्टी',
      'location_insights': 'स्थान अंतर्दृष्टी',
      'export_data': 'डेटा निर्यात करा',
      'generate_report': 'अहवाल तयार करा',

      // AI Insights
      'ai_insights': 'एआय अंतर्दृष्टी',
      'crop_age': 'पिकाचे वय',
      'growth_stage': 'वाढीचा टप्पा',
      'recommendations': 'शिफारशी',
      'days_old': 'दिवस जुने',
      'days_to_harvest': 'कापणीला दिवस',

      // Messages
      'data_saved_successfully': 'डेटा यशस्वीरित्या जतन केला',
      'data_updated_successfully': 'डेटा यशस्वीरित्या अपडेट केला',
      'verification_completed': 'सत्यापन पूर्ण झाले',
      'please_fill_all_fields': 'कृपया सर्व आवश्यक फील्ड भरा',
      'invalid_aadhaar': 'अवैध आधार क्रमांक (१२ अंक असणे आवश्यक आहे)',
      'invalid_pincode': 'अवैध पिन कोड (६ अंक असणे आवश्यक आहे)',
      'invalid_phone': 'अवैध फोन क्रमांक (१० अंक असणे आवश्यक आहे)',
      'location_permission_required': 'स्थान परवानगी आवश्यक आहे',
      'image_upload_failed': 'प्रतिमा अपलोड अयशस्वी',
      'no_data_found': 'कोणताही डेटा सापडला नाही',
      'search_farmers_placeholder': 'नाव किंवा आयडीने शोधा...',
      'filter_by_location': 'स्थानानुसार फिल्टर करा',

      // Status
      'pending': 'प्रलंबित',
      'verified': 'सत्यापित',
      'rejected': 'नाकारले',

      // Growth Stages
      'germination': 'अंकुरण',
      'vegetative': 'पर्णवृद्धी',
      'flowering': 'फुलोरा',
      'fruiting': 'फलन',
      'harvesting': 'कापणी',
      'mature': 'प्रौढ',

      // Common
      'loading': 'लोड होत आहे...',
      'error': 'त्रुटी',
      'success': 'यश',
      'warning': 'चेतावणी',
      'info': 'माहिती',
      'confirm': 'पुष्टी करा',
      'delete': 'हटवा',
      'edit': 'संपादन करा',
      'view': 'पहा',
      'back': 'मागे',
      'next': 'पुढे',
      'previous': 'मागील',
      'close': 'बंद करा',
      'ok': 'ठीक आहे',
      'yes': 'होय',
      'no': 'नाही',

      // Additional keys for dashboard screens
      'welcome': 'स्वागत',
      'home': 'मुख्यपृष्ठ',
      'location': 'स्थान',
      'quick_actions': 'त्वरित कृती',
      'recent_crops': 'अलीकडील पिके',
      'no_crops_found': 'कोणतीही पिके सापडली नाहीत',
      'no_crops_found_filter':
          'आपल्या फिल्टरशी जुळणारी कोणतीही पिके सापडली नाहीत.',
      'no_crops_for_insights': 'अंतर्दृष्टीसाठी कोणतीही पिके उपलब्ध नाहीत',
      'add_first_crop': 'आपले पहिले पिक जोडा',
      'error_loading_crops': 'पिके लोड करण्यात त्रुटी',
      'edit_profile': 'प्रोफाइल संपादन करा',
      'add_crop': 'पिक जोडा',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'help_support': 'मदत आणि समर्थन',
      'about': 'बद्दल',

      // Dashboard greetings and other static strings
      'good_morning': 'शुभ प्रभात!',
      'good_afternoon': 'शुभ दुपार!',
      'good_evening': 'शुभ संध्या!',
      'start_farming_journey':
          'आपली शेती यात्रा आपल्या पहिल्या पिकाने सुरू करा',
      'my_crops': 'माझी पिके',
      'total_area': 'एकूण क्षेत्र',
      'acres': 'एकर',

      // Registration
      'registration': 'नोंदणी',
      'personal_information': 'वैयक्तिक माहिती',
      'address_information': 'पत्ता माहिती',
      'full_name': 'पूर्ण नाव',
      'name_required': 'नाव आवश्यक आहे',
      'phone_required': 'फोन क्रमांक आवश्यक आहे',
      'aadhaar_required': 'आधार क्रमांक आवश्यक आहे',
      'village_required': 'गाव आवश्यक आहे',
      'taluka_required': 'तालुका आवश्यक आहे',
      'district_required': 'जिल्हा आवश्यक आहे',
      'pincode_required': 'पिन कोड आवश्यक आहे',
      'register': 'नोंदणी करा',
      'already_have_account': 'आधीपासून खाते आहे?',

      // New keys for onboarding/registration
      'choose_language': 'भाषा निवडा',
      'please_provide_basic_info': 'कृपया आपली मूलभूत माहिती द्या',
      'email': 'ईमेल',
      'please_provide_address': 'कृपया आपला पत्ता द्या',
      'create_secure_password': 'सुरक्षित पासवर्ड तयार करा',
      'agree_terms': 'मी नियम व अटींना सहमती देतो',

      // New key for search farmer
      'search_farmer': 'शेतकरी शोधा',
      'search_crops': 'पिके शोधा',
      'view_reports': 'अहवाल पहा',

      // OTP & Mobile Verification
      'smart_farming_management': 'स्मार्ट फार्मिंग व्यवस्थापन',
      'mobile_verification': 'मोबाइल सत्यापन',
      'enter_mobile_number': 'ओटीपी मिळवण्यासाठी आपला मोबाइल नंबर प्रविष्ट करा',
      'enter_mobile_number_hint': 'आपला 10-अंकी मोबाइल नंबर प्रविष्ट करा',
      'please_enter_mobile_number': 'कृपया आपला मोबाइल नंबर प्रविष्ट करा',
      'mobile_number_must_be_10_digits': 'मोबाइल नंबर 10 अंकांचा असावा',
      'otp': 'ओटीपी',
      'enter_otp': 'ओटीपी प्रविष्ट करा',
      'enter_otp_hint': '6-अंकी ओटीपी प्रविष्ट करा',
      'please_enter_valid_otp': 'कृपया वैध 6-अंकी ओटीपी प्रविष्ट करा',
      'send_otp': 'ओटीपी पाठवा',
      'verify_otp': 'ओटीपी सत्यापित करा',
      'resend_otp': 'ओटीपी पुन्हा पाठवा',
      'back_to_mobile_number': 'मोबाइल नंबरवर परत जा',
      'enter_otp_message': '{number} वर पाठवलेला 6-अंकी ओटीपी प्रविष्ट करा',
      // General
      'mobile_number': 'मोबाईल नंबर',
      'security': 'सुरक्षा',
      // Maharashtra Districts
      'Maharashtra': 'महाराष्ट्र',
      'Ahmednagar': 'अहमदनगर',
      'Akola': 'अकोला',
      'Amravati': 'अमरावती',
      'Aurangabad': 'औरंगाबाद',
      'Beed': 'बीड',
      'Bhandara': 'भंडारा',
      'Buldhana': 'बुलढाणा',
      'Chandrapur': 'चंद्रपूर',
      'Dhule': 'धुळे',
      'Gadchiroli': 'गडचिरोली',
      'Gondia': 'गोंदिया',
      'Hingoli': 'हिंगोली',
      'Jalgaon': 'जळगाव',
      'Jalna': 'जालना',
      'Kolhapur': 'कोल्हापूर',
      'Latur': 'लातूर',
      'Mumbai City': 'मुंबई शहर',
      'Mumbai Suburban': 'मुंबई उपनगर',
      'Nagpur': 'नागपूर',
      'Nanded': 'नांदेड',
      'Nandurbar': 'नंदुरबार',
      'Nashik': 'नाशिक',
      'Osmanabad': 'उस्मानाबाद',
      'Parbhani': 'परभणी',
      'Pune': 'पुणे',
      'Raigad': 'रायगड',
      'Ratnagiri': 'रत्नागिरी',
      'Sangli': 'सांगली',
      'Satara': 'सातारा',
      'Sindhudurg': 'सिंधुदुर्ग',
      'Solapur': 'सोलापूर',
      'Thane': 'ठाणे',
      'Wardha': 'वर्धा',
      'Washim': 'वाशीम',
      'Yavatmal': 'यवतमाळ',
      // Maharashtra Talukas/Cities
      'Shrirampur': 'श्रीरामपुर',
      'Rahata': 'राहता',
      'Rahuri': 'राहुरी',
      'Sangamner': 'संगमनर',
      'Kopargaon': 'कोपरगाव',
      'Akole': 'अकोला',
      'Nevasa': 'नेवासा',
      'Shevgaon': 'शेवगाव',
      'Pathardi': 'पाठर्दी',
      'Parner': 'परनर',
      'Jamkhed': 'जामखेड',
      'Balapur': 'बलपुर',
      'Patur': 'पाटूर',
      'Telhara': 'टेलहरा',
      'Akot': 'अकोट',
      'Murtijapur': 'मुर्तिजपुर',
      'Chandur Railway': 'चंदुर रेलवे',
      'Chikhaldara': 'चिकखलदारा',
      'Daryapur': 'दर्यापुर',
      'Dhamangaon Railway': 'धामागंव रेलवे',
      'Morshi': 'मोर्शी',
      'Nandgaon-Khandeshwar': 'नंदगाव-खंडेशवर',
      'Anjangaon Surji': 'अंजंगाव सुर्जी',
      'Achalpur': 'अचलपुर',
      'Gangapur': 'गंगापुर',
      'Vaijapur': 'वैजापुर',
      'Sillod': 'सिलोड',
      'Kannad': 'कन्नाड',
      'Paithan': 'पैथान',
      'Khuldabad': 'खुलढाबाद',
      'Phulambri': 'फुलम्बरी',
      'Ashti': 'अश्ती',
      'Ambejogai': 'अम्बेजोगै',
      'Patoda': 'पाटोदा',
      'Kaij': 'कैज',
      'Georai': 'गेओराई',
      'Majalgaon': 'मजलागाव',
      'Parli': 'परली',
      'Shirur (Beed)': 'शिरुर (बीड)',
      'Tumsar': 'तुमसर',
      'Sakoli': 'साकोली',
      'Lakhani': 'लाखानी',
      'Mohadi': 'मोहादी',
      'Pauni': 'पौनी',
      'Chikhli': 'चिकखली',
      'Mehkar': 'मेहकर',
      'Jalgaon Jamod': 'जलगांव जामोड',
      'Sangrampur': 'संगरमपुर',
      'Malkapur': 'मलकपुर',
      'Deulgaon Raja': 'देवलगाव राजा',
      'Motala': 'मोतला',
      'Nandura': 'नंदुरा',
      'Shegaon': 'शेगाव',
      'Warora': 'वरोरा',
      'Bhadravati': 'भद्रावती',
      'Chimur': 'चिमुर',
      'Nagbhid': 'नागभिद',
      'Mul': 'मुल',
      'Saoli': 'सावोली',
      'Rajura': 'राजुरा',
      'Pombhurna': 'पोम्बुर्ना',
      'Ballarpur': 'बलरपुर',
      'Gondpipri': 'गोंदपिरी',
      'Korpana': 'कोरपाना',
      'Shirpur': 'शिरपुर',
      'Sakri': 'साकरी',
      'Sindkheda': 'सिंधकेडा',
      'Aheri': 'अहेरी',
      'Chamorshi': 'चामोर्शी',
      'Etapalli': 'एटापली',
      'Armori': 'अर्मोरी',
      'Desaiganj (Wadsa)': 'देसागंज (वाडसा)',
      'Korchi': 'कोरची',
      'Kurkheda': 'कुर्खेडा',
      'Mulchera': 'मुलचेरा',
      'Tirora': 'तिरोरा',
      'Goregaon': 'गोरेगाव',
      'Amgaon': 'अमगाव',
      'Arjuni Morgaon': 'अर्जुनी मोरगाव',
      'Deori': 'देवोरी',
      'Sadak Arjuni': 'सादक अर्जुनी',
      'Salekasa': 'सलेकासा',
      'Kalamnuri': 'कालमनुरी',
      'Basmath': 'बस्मात',
      'Sengaon': 'सेंगाव',
      'Bhusawal': 'भुसावल',
      'Jamner': 'जामनर',
      'Chalisgaon': 'चलिसगाव',
      'Erandol': 'एरंदोल',
      'Yawal': 'यावल',
      'Amalner': 'अमलनर',
      'Pachora': 'पचोरा',
      'Parola': 'परोला',
      'Dharangaon': 'धारंगाव',
      'Bhokardan': 'भोकरदान',
      'Jaffrabad': 'जफ्राबाद',
      'Ambad': 'अम्बाद',
      'Badnapur': 'बदनपुर',
      'Mantha': 'मंथा',
      'Partur': 'पारतूर',
      'Ghansawangi': 'घंसावांगी',
      'Karveer': 'कर्वेयर',
      'Gaganbawada': 'गगनबावदा',
      'Radhanagari': 'राधानागरी',
      'Ajra': 'अज्रा',
      'Bhudargad': 'भुदारगड',
      'Chandgad': 'चंदगड',
      'Gadhinglaj': 'गढ़िंगलाज',
      'Hatkanangale': 'हटकानांगाले',
      'Kagal': 'कागल',
      'Panhala': 'पांहाला',
      'Shirol': 'शिरोल',
      'Ahmadpur': 'अहमदपुर',
      'Udgir': 'उद्गिर',
      'Nilanga': 'निलंगा',
      'Ausa': 'अवुसा',
      'Chakur': 'चकुर',
      'Deoni': 'देओनी',
      'Renapur': 'रेनापुर',
      'Shirur Anantpal': 'शिरुर अनन्तपाल',
      'Katol': 'काटोल',
      'Narkhed': 'नरखेड',
      'Kalmeshwar': 'कालमेशवर',
      'Hingna': 'हिंगना',
      'Umred': 'उमरेड',
      'Parseoni': 'परेसोनी',
      'Ramtek': 'रामटेक',
      'Bhiwapur': 'भिवावुर',
      'Kuhi': 'कुही',
      'Mauda': 'मौदा',
      'Kinwat': 'किनवत',
      'Hadgaon': 'हदगाव',
      'Bhokar': 'भोकर',
      'Loha': 'लोहा',
      'Naigaon': 'नाइगाव',
      'Mukhed': 'मुखेड',
      'Deglur': 'देगलूर',
      'Kandhar': 'कंधर',
      'Himayatnagar': 'हिमायतनगर',
      'Shahada': 'शाहदा',
      'Taloda': 'तालोदा',
      'Navapur': 'नवपुर',
      'Akkalkuwa': 'अक्कलकुवा',
      'Akrani (Dhadgaon)': 'अक्रनी (धादगाव)',
      'Malegaon': 'मलेगाव',
      'Sinnar': 'सिननर',
      'Igatpuri': 'इगतपुरी',
      'Kalwan': 'कालवान',
      'Dindori': 'दिनदोरी',
      'Chandwad': 'चंदवद',
      'Deola': 'देओला',
      'Niphad': 'निपहाड',
      'Peth': 'पेट',
      'Trimbakeshwar': 'त्रिम्बकेशवर',
      'Baglan': 'बागलन',
      'Yevla': 'येवला',
      'Tuljapur': 'तुलजपुर',
      'Paranda': 'परंदा',
      'Bhum': 'भूम',
      'Kalamb': 'कालंब',
      'Lohara': 'लोहारा',
      'Umarga': 'उमारगा',
      'Vashi': 'वाशी',
      'Gangakhed': 'गंगकेड',
      'Pathri': 'पाठ्री',
      'Sonpeth': 'सोनपेट',
      'Manwat': 'मनवत',
      'Jintur': 'जिंतूर',
      'Purna': 'पुरंदा',
      'Palam': 'पालम',
      'Sailu': 'सैलु',
      'Pune City': 'पुणे शहर',
      'Haveli': 'हवेली',
      'Mulshi': 'मुलशी',
      'Bhor': 'भोर',
      'Baramati': 'बरामती',
      'Indapur': 'इंदापुर',
      'Junnar': 'जुन्नार',
      'Daund': 'दौंड',
      'Ambegaon': 'अम्बेगाव',
      'Shirur': 'शिरुर',
      'Velhe': 'वेले',
      'Purandar': 'पुरंदार',
      'Mawal': 'मवल',
      'Khed': 'खेड',
      'Alibag': 'अलिबाग',
      'Pen': 'पेन',
      'Mahad': 'महादेव',
      'Murud': 'मुरुद',
      'Roha': 'रोहा',
      'Shrivardhan': 'श्रीवर्धन',
      'Tala': 'ताला',
      'Uran': 'उराण',
      'Karjat': 'कर्जत',
      'Khalapur': 'खलपुर',
      'Mangaon': 'मंगाव',
      'Poladpur': 'पोलदपुर',
      'Sudhagad Pali': 'सुधागद पाली',
      'Mandangad': 'मंदंगाड',
      'Dapoli': 'दापोली',
      'Guhagar': 'गुहागर',
      'Chiplun': 'चिपलुंड',
      'Sangameshwar': 'संगमेशवर',
      'Lanja': 'लांजा',
      'Rajapur': 'राजापुर',
      'Miraj': 'मिराज',
      'Tasgaon': 'तसगाव',
      'Kavathemahankal': 'कावथेमहांकल',
      'Jath': 'जठ',
      'Khanapur': 'खानपुर',
      'Palus': 'पालुस',
      'Atpadi': 'अत्पाडी',
      'Walwa': 'वालवा',
      'Shirala': 'शिरला',
      'Karad': 'कराड',
      'Wai': 'वै',
      'Patan': 'पाटन',
      'Mahabaleshwar': 'महाभालेश्वर',
      'Phaltan': 'फाल्टन',
      'Khatav': 'खटवा',
      'Koregaon': 'कोरेगाव',
      'Jaoli': 'जावली',
      'Man': 'मान',
      'Kudal': 'कुडल',
      'Sawantwadi': 'सावंतवाडी',
      'Dodamarg': 'दोदामारग',
      'Vengurla': 'वेंगुरला',
      'Malvan': 'मल्वान',
      'Devgad': 'देवगड',
      'Kankavli': 'कंकवली',
      'Solapur North': 'सोलापुर उत्तर',
      'Solapur South': 'सोलापुर दक्षिण',
      'Barshi': 'बर्शी',
      'Madha': 'मधा',
      'Karmala': 'कर्माला',
      'Mohol': 'मोहोल',
      'Pandharpur': 'पंधारपुर',
      'Sangole': 'संगोले',
      'Akkalkot': 'अक्कलकोट',
      'Malshiras': 'मल्शिरस',
      'Kalyan': 'कल्याण',
      'Bhiwandi': 'भिवाणदी',
      'Murbad': 'मुर्बाद',
      'Ulhasnagar': 'उल्हसनगर',
      'Ambarnath': 'अम्बरनाथ',
      'Shahapur': 'शाहपुर',
      'Hinganghat': 'हिंगंगट',
      'Deoli': 'देओली',
      'Arvi': 'अर्वी',
      'Seloo': 'सेलू',
      'Samudrapur': 'समुद्रपुर',
      'Mangrulpir': 'मंगरुल्पिर',
      'Karanja': 'करंजा',
      'Manora': 'मनोरा',
      'Malegaon (Washim)': 'मलेगाव (वाशिम)',
      'Risod': 'रिसोड',
      'Pusad': 'पुसाड',
      'Umarkhed': 'उमरकड',
      'Digras': 'दिग्रस',
      'Arni': 'अर्नी',
      'Darwha': 'दर्वाहा',
      'Kelapur': 'केलापुर',
      'Ghatanji': 'घटानजी',
      'Ner': 'नेर',
      'Mahagaon': 'महागाव',
      'Ralegaon': 'रालेगाव',
      'Babulgaon': 'बाबुलगाव',

      // help and support
      // 'help_support': 'Help & Support',
      'how_can_we_help': 'How can we help you?',
      'help_support_description':
          'We\'re here to assist you with any questions or issues you may have.',
      'quick_help': 'Quick Help',
      'faqs': 'FAQs',
      'video_tutorials': 'Video Tutorials',
      'user_guide': 'User Guide',
      'contact_support': 'Contact Support',
      'email_us': 'Email Us',
      'call_us': 'Call Us',
      'live_chat': 'Live Chat',
      'available_24_7': 'Available 24/7',
      'community': 'Community',
      'community_forum': 'Community Forum',
      'facebook_group': 'Facebook Group',
      'report_problem': 'Report a Problem',
    },
  };

  static String getString(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']![key] ?? key;
  }
}
